const UNEXPECTED_ERROR=-1;
const DATA_NOT_FOUND=0
const OK=1;
const PAGINATION_MAX_RECORD_SIZE=10;

const ALLOWED_EXTENSIONS="PNG,JPEG,JPG";
const MONTH_ARRAY=['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];


module.exports={UNEXPECTED_ERROR, DATA_NOT_FOUND, OK, ALLOWED_EXTENSIONS,MONTH_ARRAY,PAGINATION_MAX_RECORD_SIZE};