const ALLOWED_EXTENSIONS="PNG,JPEG,JPG";
const MONTH_ARRAY=['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];


const PAGINATION_MAX_RECORD_SIZE=10;


const OK=200;
const UNAUTHORIZED=400;
const INVALID=401;
const NOT_FOUND=404;

module.exports={ALLOWED_EXTENSIONS,MONTH_ARRAY,PAGINATION_MAX_RECORD_SIZE,OK,UNAUTHORIZED,INVALID, NOT_FOUND};